Food/urls.py
from django.urls import path
from .  import views

app_name = "Food"
urlpatterns = [
    path("",views.IndexClassView.as_view(),name = "index"),
    path("item/",views.item,name = "item"),
    path("<int:pk>",views.DetailClassView.as_view(), name = "details"),
    path("add/",views.CreateItem.as_view(), name = "create_item"),
    path("update/<int:id>/",views.update_item,name = "update_item"),
    path("delete/<int:id>",views.delete_item,name = "delete_item")
]

Foodorder/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin



admin.autodiscover()
urlpatterns = [
    path('',include("Food.urls")),
    path("register/",user_views.register, name = "register"),
    path('admin/', admin.site.urls),
    path("login/",views.LoginView.as_view(template_name = "user/login.html"),name = "login_view"),
    path("logout/",views.LogoutView.as_view(template_name = "user/logout.html"),name = "logout"),
    path("profile/",user_views.profilepage,name = "profile"),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Item(models.Model):
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField("Item Name",max_length=200)
    item_desc = models.CharField("Item Discription",max_length=200)
    item_price = models.IntegerField("Item Price")
    item_image = models.CharField("Item Image",max_length=200,default="https://image.flaticon.com/icons/svg/1344/1344788.svg")


    def __str__(self):
        return self.item_name
    
    def get_absolute_url(self):
        return reverse("Food:details",kwargs = {"pk":self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User


class profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default="profile.jpg",upload_to="profile_pictures")
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

Food/forms.py
from django import forms
from .models import Item

class ItemFrom(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name","item_desc","item_price","item_image"]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ["username","email","password1","password2"]

Food/views.py
from django.shortcuts import render,redirect
from .forms import ItemFrom
from django.http import HttpResponse
from .models import Item
from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.

# def index(request):
#     item_list = Item.objects.all()
#     # template = loader.get_template("Food/index.html")
#     context = {
#         "item_list" :item_list
#     }
#     return render(request,"Food/index.html",context)
#     # return HttpResponse(template.render(context,request))

class IndexClassView(ListView):
    model = Item
    template_name = "Food/index.html"
    context_object_name = "item_list"

def item(request):
    return HttpResponse("<h1>this is an item view</h1>")

# def detail(request,item_id):
#     item = Item.objects.get(pk=item_id)
#     context = {
#         "item" : item
#     }
#     return render(request,"Food/details.html",context)

class DetailClassView(DetailView):
    model = Item
    template_name = "Food/details.html"



# def create_item(request):
#     form = ItemFrom(request.POST or None)
#     if form.is_valid():
#         form.save()
#         return redirect("Food:index")
#     return render(request,"Food/item_form.html",{"form" : form})

class CreateItem(CreateView):
    model = Item
    fields = ["item_name","item_desc","item_price","item_image"]
    template_name = "Food/item_form.html"

    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemFrom(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect("Food:index")
    return render(request,"Food/item_form.html",{"form" : form,"item" : item})

def delete_item(request,id):
    item = Item.objects.get(id=id)
    if request.method == "POST":
        item.delete()
        return redirect("Food:index")
    return render(request,"Food/item_delete.html",{ "item" : item })
    

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request,"welcome " + username + " your account has been created" )
            return redirect("login_view")
    else:
        form = RegisterForm()
    return render(request,"user/register.html",{"form" : form})

@login_required
def profilepage(request):
    return render(request,"user/profile.html")

Food/templates/Food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a href="#" class="navbar-brand">FOODAPP</a>
        <div class="navbar">
            <a href="#" class="navbar-item nav-link">Menu Item</a>
            <a href="{% url "Food:create_item" %}" class="navbar-item nav-link">Add Item</a>
            <a href="#" class="navbar-item nav-link">Delete Item</a>
            {% if user.is_authenticated %}
                <a href="{% url "logout"%}" class="navbar-item nav-link">Logout</a>
                <a href="{% url "profile"%}" class="navbar-item nav-link">Profile</a>
            {% else %}
                <a href="{% url "login_view"%}" class="navbar-item nav-link">Login</a>
            {% endif %}
        </div>
    </nav>
    {%  if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tag }}">
            {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock%}
</body>
</html>

Food/templates/Food/details.html
{% extends "Food/base.html" %}
{% load static %}
{% block body %}
    <div class="container">
         <div class="row">
            <div class="col-md-6">
                <img class="card" height="150px" src = "{{ item.item_image }}"/>
            </div>
            <div class="col-md-6">
                <h3> {{ object.item_name }}</h3>
                <h5> {{ object.item_desc }}</h5>
                <h6> {{ object.item_price }}</h6>
                <a href="{% url "Food:delete_item" object.id %}"> delete</a>
            </div>
        </div>
    </div>
{% endblock %}

Food/templates/Food/index.html
{% extends "Food/base.html" %}
{% load static %}
{% block body %}
{% for item in item_list %}
    <link rel="stylesheet" href = "{% static "Food/style.css" %}">

    <div class="row">
    <div class="col-md-3 offset-md-2 col-mt-5">
        <img class="card" height="150px" src = "{{ item.item_image }}"/>
    </div>
    <div class="col-md-4">
        <h3> {{ item.item_name }}</h3>
        <h5> {{ item.item_desc }}</h5>
        <h6> {{ item.item_price }}</h6>
        <h6> {{ item.user_name }}</h6>
    </div>
    <div class="col-md-2">
        <a href ="{% url "Food:details" item.id %}" class = "btn btn-success">Details</a>

    </div>
    </div>
{% endfor %}
{% endblock %}

Food/templates/Food/item_delete.html
{% extends "Food/base.html" %}
{% load static %}
{% block body %}
<form method="POST">
{% csrf_token %}
<h1 class = "text-center pt-20"> are you sure you want to delete item ?</h1>
<button type="submit" class = "btn btn-primary center" style="text-align:center"> confirm</button>
</form>
{% endblock %}

Food/templates/Food/item_form.html
{% extends "Food/base.html" %}
{% block body %}
<form method="POST">
{% csrf_token %}
  <div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
          <div class="card-header">
              <div class="card-title text-center bg-info">
                login
              </div>
              <div class="card-body">
                 {% for field in  form %}
                 <div class="form-group">
                  {{ field.label }}
                  <br>
                  {{ field }}
                </div>
                 {% endfor %}
                 <button type="submit">submit</button>
                 </form>
              </div>
           </div>
        </div>
    </div>
  </div>
{% endblock %}

users/templates/user/login.html
{% extends "Food/base.html" %}
{% block body %}
<form method="POST">
{% csrf_token %}
  <div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
          <div class="card-header">
              <div class="card-title text-center bg-info">
                login
              </div>
              <div class="card-body">
                 {{ form.as_table }}
                 <button type="submit">submit</button>
                 </form>
              </div>
           </div>
        </div>
    </div>
  </div>
{% endblock %}

users/templates/user/logout.html
<h1> user is logedout </h1>

users/templates/user/profile.html
{% load static %}
<h1> {{ user.username }}</h1>
<img src="{{ user.profile.image.url }}"> </img>

users/templates/user/register.html
{% extends "Food/base.html" %}
{% block body %}
<form method="POST">
{% csrf_token %}
  <div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
          <div class="card-header">
              <div class="card-title text-center bg-info">
                login
              </div>
              <div class="card-body">
                 {% for field in  form %}
                 <div class="form-group">
                  {{ field.name }}
                  <br>
                  {{ field }}
                </div>
                 {% endfor %}
                 <button type="submit">submit</button>
                 </form>
              </div>
           </div>
        </div>
    </div>
  </div>
{% endblock %}